# Control Flow

Bottom line up front, Python is weird about groupings. Instead of using braces
and making things clear and explicit, Python enforces indentation as a way of
grouping code. What this means if you have both spaces and tabs is unclear, but
it's certainly going to get confusing. Add to this Python's mixed bag when it
comes to putting function arguments in brackets and we've got a real mess.

## If statements

The general syntax for an if statement is:

```
if condition :
    execute this
    and this because we're still indented
execute this regardless because we've got no indent
```
The general syntax for an if else statement is:

```
if condition :
    execute this
else :
    execute this
```
The general syntax for an else if statement is:

```
if condition :
    execute this
elif condition :
    execute this
else :
    execute this
```
## While loop

The general syntax for a while loop is:

```
while condition :
    expression
```

## For loop

The general syntax for a for loop is:

```
for var in seq :
    expression
```

You can also do inline enumeration if you want to (to get access to the index
as well as the value), but it's a bit flimsy and hard to understand because it
only exists in the for loop syntax (so you can't easily debug how it works):

```
for index, var in enumerate(seq):
    expression
```

You can also iterate along multiple columns in nested lists:

```
for room, area in house :
    expression
```

To iterate through the rows of a pandas DataFrame, you can use the following:

```
for lab, row in df.iterrows() :
    print(lab) # The row label
    print(row) # The pandas Series, i.e. a named list consisting of the row elements
```
    
    
    